server:
  port: 8081

spring:
  application:
    name: POST-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
    instance:
      hostname: localhost