server:
  port: 8084

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST

      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: POST-SERVICE
          uri: lb://POST-SERVICE
          predicates:
              - Path=/posts/**
        - id: SONG-SERVICE
          uri: lb://SONG-SERVICE
          predicates:
              - Path=/songs/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
    instance:
      hostname: localhost